### ISSUE TITLE
Display of labels?

### ISSUE THREAD

**Issue by 0xdeadf00d** [OpenKieler/klayjs-d3#14]
Hi there,

thanks for the cool library.

I have an issue with labels (maybe I just need a pointer at the right example/documentation).

As I understand, in the examples, only the ids of the nodes are displayed
(i.e. converted to text elements in svg).
Labels from the JSON graph are ignored. Is that right?
If so, how would I display the labels instead of the Ids?

Cheers,
Alex

**Comment by uruuru** [comment]
If I understand you correctly, it's a matter of what you tell d3 to turn into text. For instance, in [line 129](https://github.com/OpenKieler/klayjs-d3/blob/master/examples/interactive/index.js#L129) of the interactive example `d.id` is used as text of the svg `text` element. IIRC you should be able to do something like `d.labels[0].text` since that specific `d` is a node element of the json graph.

**Comment by 0xdeadf00d** [comment]
Hi Ulf,

thanks for your reply. In your approach, the label/text placement is hard coded in the .js.

Does that mean that automatic label placement as described at [https://rtsys.informatik.uni-kiel.de/confluence/display/KIELER/Label+Placement%2C+Port+Placement+and+Node+Sizing](https://rtsys.informatik.uni-kiel.de/confluence/display/KIELER/Label+Placement%2C+Port+Placement+and+Node+Sizing) is not supported in klayjs?

Thanks in advance,
Alex

**Comment by uruuru** [comment]
It's supported. I created a small [example ](http://openkieler.github.io/klayjs-d3/examples/node_labels/) that seems to work properly.

**Comment by 0xdeadf00d** [comment]
Thanks, and sorry for the late reply.
It seems that github doesn't send emails on edited comments.

**Comment by uruuru** [comment]
Good to know, sorry for just editing.
